import type { Art } from '@/types/art'
import type { CommissionService } from '@/types/commission'
import type { ChapterItem, WorkItem } from '@/features/work/hooks/useHome'

export const SAMPLE_NOW = '2026-07-28T10:00:00.000Z'

export function samplePageImage(label: string, from = '#56b6ff', to = '#ff8a00') {
    const safeLabel = label.replace(/[<>&"']/g, '')

    return `data:image/svg+xml,${encodeURIComponent(
        `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 860"><defs><linearGradient id="g" x1="0" x2="1" y1="0" y2="1"><stop stop-color="${from}"/><stop offset="1" stop-color="${to}"/></linearGradient></defs><rect width="640" height="860" rx="54" fill="url(#g)"/><circle cx="500" cy="160" r="88" fill="rgba(255,255,255,.35)"/><circle cx="140" cy="700" r="120" fill="rgba(255,255,255,.22)"/><text x="50%" y="50%" text-anchor="middle" font-family="Inter,Arial,sans-serif" font-size="54" font-weight="800" fill="white">${safeLabel}</text><text x="50%" y="58%" text-anchor="middle" font-family="Inter,Arial,sans-serif" font-size="24" fill="rgba(255,255,255,.82)">Temporary preview</text></svg>`
    )}`
}

export const SAMPLE_WORKS: WorkItem[] = [
    {
        id: 'sample-comix-1',
        slug: 'sample-comix',
        title: 'Sample Comix Feature',
        cover: samplePageImage('Comix', '#54b6ff', '#ff477e'),
        banner: samplePageImage('Comix Hero', '#0ea5e9', '#f97316'),
        type: 'webtoon',
        content_type: 'work',
        genres: ['Action', 'Fantasy'],
        views: 13200,
        likes: 920,
        period_views: 320,
        period_likes: 52,
        weekly_views: 1880,
        created_at: SAMPLE_NOW,
        status: 'ongoing',
        is_featured: true,
    },
    {
        id: 'sample-comix-2',
        slug: 'sample-romance-comix',
        title: 'Sample Romance Comix',
        cover: samplePageImage('Romance', '#fb7185', '#fbbf24'),
        banner: samplePageImage('Romance Hero', '#f472b6', '#38bdf8'),
        type: 'webtoon',
        content_type: 'work',
        genres: ['Romance', 'Drama'],
        views: 7600,
        likes: 640,
        period_views: 180,
        period_likes: 31,
        weekly_views: 1140,
        created_at: SAMPLE_NOW,
        status: 'ongoing',
        is_featured: false,
    },
    {
        id: 'sample-novel-1',
        slug: 'sample-novel',
        title: 'Sample Novel Spotlight',
        cover: samplePageImage('Novel', '#8b5cf6', '#06b6d4'),
        banner: samplePageImage('Novel Hero', '#6366f1', '#ec4899'),
        type: 'wattpad',
        content_type: 'work',
        genres: ['Mystery', 'Sci-Fi'],
        views: 9800,
        likes: 810,
        period_views: 240,
        period_likes: 45,
        weekly_views: 1410,
        created_at: SAMPLE_NOW,
        status: 'ongoing',
        is_featured: true,
    },
    {
        id: 'sample-art-1',
        slug: 'sample-art',
        title: 'Sample Art Preview',
        cover: samplePageImage('Art', '#22c55e', '#f97316'),
        banner: samplePageImage('Art Hero', '#14b8a6', '#f43f5e'),
        type: 'art',
        content_type: 'art',
        genres: ['Fanart', 'Original'],
        views: 5600,
        likes: 430,
        period_views: 95,
        period_likes: 22,
        created_at: SAMPLE_NOW,
        status: 'published',
        is_featured: true,
    },
    ...Array.from({ length: 6 }, (_, index): WorkItem => {
        const isNovel = index % 3 === 1
        const isArt = index % 3 === 2
        const label = isArt ? 'Art' : isNovel ? 'Novel' : 'Comix'
        const id = `sample-${label.toLowerCase()}-${index + 3}`

        return {
            id,
            slug: id,
            title: `Sample ${label} ${index + 3}`,
            cover: samplePageImage(`${label} ${index + 3}`, '#38bdf8', '#fb7185'),
            banner: samplePageImage(`${label} Hero`, '#f97316', '#0ea5e9'),
            type: isArt ? 'art' : isNovel ? 'wattpad' : 'webtoon',
            content_type: isArt ? 'art' : 'work',
            genres: isArt ? ['Original', 'Illustration'] : isNovel ? ['Fantasy', 'Mystery'] : ['Action', 'Adventure'],
            views: 2500 + index * 980,
            likes: 120 + index * 85,
            period_views: 30 + index * 24,
            period_likes: 8 + index * 6,
            weekly_views: 340 + index * 190,
            created_at: SAMPLE_NOW,
            status: isArt ? 'published' : index % 2 === 0 ? 'ongoing' : 'completed',
            is_featured: index % 2 === 0,
        }
    }),
]

export const SAMPLE_CHAPTERS: ChapterItem[] = [
    {
        id: 'sample-chapter-1',
        work_id: 'sample-comix-1',
        title: 'Chapter 1: Preview Opening',
        cover: samplePageImage('Ch. 1', '#54b6ff', '#ff477e'),
        order: 1,
        created_at: SAMPLE_NOW,
        work: {
            id: 'sample-comix-1',
            slug: 'sample-comix',
            title: 'Sample Comix Feature',
            cover: samplePageImage('Comix', '#54b6ff', '#ff477e'),
            type: 'webtoon',
        },
    },
    {
        id: 'sample-chapter-2',
        work_id: 'sample-novel-1',
        title: 'Episode 2: The Quiet Signal',
        cover: samplePageImage('Ep. 2', '#8b5cf6', '#06b6d4'),
        order: 2,
        created_at: SAMPLE_NOW,
        work: {
            id: 'sample-novel-1',
            slug: 'sample-novel',
            title: 'Sample Novel Spotlight',
            cover: samplePageImage('Novel', '#8b5cf6', '#06b6d4'),
            type: 'wattpad',
        },
    },
    ...Array.from({ length: 8 }, (_, index): ChapterItem => {
        const isNovel = index % 2 === 1
        const workId = isNovel ? 'sample-novel-1' : 'sample-comix-1'

        return {
            id: `sample-chapter-${index + 3}`,
            work_id: workId,
            title: `${isNovel ? 'Episode' : 'Chapter'} ${index + 3}: Preview Update`,
            cover: samplePageImage(`Ch. ${index + 3}`, isNovel ? '#8b5cf6' : '#54b6ff', '#f97316'),
            order: index + 3,
            created_at: SAMPLE_NOW,
            work: {
                id: workId,
                slug: isNovel ? 'sample-novel' : 'sample-comix',
                title: isNovel ? 'Sample Novel Spotlight' : 'Sample Comix Feature',
                cover: samplePageImage(isNovel ? 'Novel' : 'Comix', '#54b6ff', '#ff477e'),
                type: isNovel ? 'wattpad' : 'webtoon',
            },
        }
    }),
]

export const SAMPLE_ARTS: Art[] = [
    {
        id: 'sample-art-post-1',
        slug: 'sample-art-post',
        title: 'Sample Character Sheet',
        description: 'Temporary art preview for empty page widgets.',
        labels: ['Fanart', 'Character Design'],
        image_path: samplePageImage('Sheet', '#0ea5e9', '#f97316'),
        images: [],
        status: 'published',
        moderation_status: 'approved',
        download_policy: 'disabled',
        download_credits: 0,
        downloads_count: 0,
        apply_watermark: false,
        views: 4200,
        likes: 610,
        comments_count: 18,
        super_likes_count: 4,
        super_like_credits: 12,
        is_featured: true,
        user: {
            id: 'sample-artist',
            name: 'Preview Artist',
            username: 'preview_artist',
            role: 'storyteller',
            avatar: samplePageImage('A', '#111827', '#f59e0b'),
            artist_verified: true,
        },
        created_at: SAMPLE_NOW,
        updated_at: SAMPLE_NOW,
    },
    {
        id: 'sample-art-post-2',
        slug: 'sample-background-art',
        title: 'Sample Background Art',
        description: 'A second temporary art sample for grids.',
        labels: ['Background', 'Original'],
        image_path: samplePageImage('BG', '#22c55e', '#06b6d4'),
        images: [],
        status: 'published',
        moderation_status: 'approved',
        download_policy: 'disabled',
        download_credits: 0,
        downloads_count: 0,
        apply_watermark: false,
        views: 3100,
        likes: 390,
        comments_count: 9,
        super_likes_count: 2,
        super_like_credits: 6,
        is_featured: false,
        user: {
            id: 'sample-artist',
            name: 'Preview Artist',
            username: 'preview_artist',
            role: 'storyteller',
            avatar: samplePageImage('A', '#111827', '#f59e0b'),
            artist_verified: true,
        },
        created_at: SAMPLE_NOW,
        updated_at: SAMPLE_NOW,
    },
    ...Array.from({ length: 8 }, (_, index): Art => ({
        id: `sample-art-post-${index + 3}`,
        slug: `sample-art-post-${index + 3}`,
        title: `Sample Art Post ${index + 3}`,
        description: 'Temporary art preview for Page Customize.',
        labels: index % 2 === 0 ? ['Fanart', 'Original'] : ['Background', 'Character Design'],
        image_path: samplePageImage(`Art ${index + 3}`, '#22c55e', '#0ea5e9'),
        images: [],
        status: 'published',
        moderation_status: 'approved',
        download_policy: 'disabled',
        download_credits: 0,
        downloads_count: index * 3,
        apply_watermark: false,
        views: 1200 + index * 410,
        likes: 90 + index * 44,
        comments_count: index + 2,
        super_likes_count: index % 3,
        super_like_credits: index * 2,
        is_featured: index % 2 === 0,
        user: {
            id: 'sample-artist',
            name: 'Preview Artist',
            username: 'preview_artist',
            role: 'storyteller',
            avatar: samplePageImage('A', '#111827', '#f59e0b'),
            artist_verified: true,
        },
        created_at: SAMPLE_NOW,
        updated_at: SAMPLE_NOW,
    })),
]

export const SAMPLE_COMMISSIONS: CommissionService[] = [
    {
        id: 'sample-commission-1',
        title: 'Sample Character Commission',
        slug: 'sample-character-commission',
        description: 'Temporary commission service for empty page widgets.',
        image_path: samplePageImage('Commission', '#fb7185', '#8b5cf6'),
        status: 'open',
        boosted_until: SAMPLE_NOW,
        base_price_credits: 30,
        min_price_credits: 30,
        delivery_days: 14,
        slots_available: 3,
        is_featured: true,
        views_count: 880,
        likes_count: 140,
        created_at: SAMPLE_NOW,
        updated_at: SAMPLE_NOW,
        flow: [
            { type: 'pay', label: 'Deposit', percent: 50 },
            { type: 'sketch', label: 'Sketch' },
            { type: 'pay', label: 'Final pay', percent: 50 },
            { type: 'done', label: 'Delivery' },
        ],
        terms: 'Sample terms for preview.',
        quote_rules: 'Quote starts from 30 credits.',
        refund_policy: 'Preview refund policy.',
        required_references: 'Character references and notes.',
        request_questions: [],
        info_questions: [],
        client_fields: {
            name: { collect: true, required: true },
            username: { collect: true, required: false },
            email: { collect: true, required: true },
            discord: { collect: true, required: false },
            twitter: { collect: false, required: false },
            instagram: { collect: false, required: false },
            facebook: { collect: false, required: false },
            tiktok: { collect: false, required: false },
        },
        promo_discounts: [],
        setup_options: {
            visibility: 'discoverable',
            service_type: 'custom',
            communication_style: 'open',
            requesting_process: 'custom_proposal',
            notify_followers_on_status_change: false,
            sensitive: false,
            display_service_stats: true,
            guaranteed_delivery_days: 14,
        },
        artist_terms: 'Preview artist terms.',
        platform_terms: ['Payments stay inside LaterNComix credits.'],
        rating_average: 5,
        ratings_count: 12,
        customers_count: 24,
        category: { id: 'sample-category', name: 'Illustration', slug: 'illustration' },
        artist: {
            id: 'sample-artist',
            name: 'Preview Artist',
            username: 'preview_artist',
            avatar: samplePageImage('A', '#111827', '#f59e0b'),
            artist_title: 'Commission Artist',
            artist_verified: true,
            commission_status: 'open',
        },
        recent_ratings: [],
    },
    ...Array.from({ length: 9 }, (_, index): CommissionService => ({
        id: `sample-commission-${index + 2}`,
        title: `Sample Commission ${index + 2}`,
        slug: `sample-commission-${index + 2}`,
        description: 'Temporary commission preview for Page Customize.',
        image_path: samplePageImage(`Comm ${index + 2}`, '#fb7185', '#8b5cf6'),
        status: index % 3 === 0 ? 'waitlist' : 'open',
        boosted_until: index % 2 === 0 ? SAMPLE_NOW : null,
        base_price_credits: 30 + index * 5,
        min_price_credits: 30 + index * 5,
        delivery_days: 7 + index,
        slots_available: Math.max(1, 5 - (index % 4)),
        is_featured: index % 2 === 0,
        views_count: 240 + index * 120,
        likes_count: 30 + index * 18,
        created_at: SAMPLE_NOW,
        updated_at: SAMPLE_NOW,
        flow: [
            { type: 'pay', label: 'Deposit', percent: 50 },
            { type: 'sketch', label: 'Sketch' },
            { type: 'pay', label: 'Final pay', percent: 50 },
            { type: 'done', label: 'Delivery' },
        ],
        terms: 'Sample terms for preview.',
        quote_rules: 'Quote starts from the listed minimum.',
        refund_policy: 'Preview refund policy.',
        required_references: 'Reference images and notes.',
        request_questions: [],
        info_questions: [],
        client_fields: {
            name: { collect: true, required: true },
            username: { collect: true, required: false },
            email: { collect: true, required: true },
            discord: { collect: true, required: false },
            twitter: { collect: false, required: false },
            instagram: { collect: false, required: false },
            facebook: { collect: false, required: false },
            tiktok: { collect: false, required: false },
        },
        promo_discounts: [],
        setup_options: {
            visibility: 'discoverable',
            service_type: 'custom',
            communication_style: 'open',
            requesting_process: 'custom_proposal',
            notify_followers_on_status_change: false,
            sensitive: false,
            display_service_stats: true,
            guaranteed_delivery_days: 14,
        },
        artist_terms: 'Preview artist terms.',
        platform_terms: ['Payments stay inside LaterNComix credits.'],
        rating_average: 4.5 + (index % 2) * 0.5,
        ratings_count: 4 + index,
        customers_count: 8 + index * 2,
        category: {
            id: `sample-category-${index % 4}`,
            name: ['Illustration', 'Character Art', 'Chibi', 'Cover Art'][index % 4],
            slug: ['illustration', 'character-art', 'chibi', 'cover-art'][index % 4],
        },
        artist: {
            id: 'sample-artist',
            name: 'Preview Artist',
            username: 'preview_artist',
            avatar: samplePageImage('A', '#111827', '#f59e0b'),
            artist_title: 'Commission Artist',
            artist_verified: true,
            commission_status: 'open',
        },
        recent_ratings: [],
    })),
]

export function withSampleList<T>(items: T[] | undefined | null, samples: T[]) {
    return items?.length ? items : samples
}
